// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";
export const AUTH_ERROR = "AUTH_ERROR";

// ACTIONS FOR PRODUCTS
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
