// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";

// ACTIONS FOR PRODUCTS
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

//ACTIONS FOR OFFERING PRODUCT
export const CREATE_OFFERING = "CREATE_OFFERING";
export const OFFERING_ERROR = "OFFERING_ERROR";
export const GET_OFFER = "GET_OFFER"
export const GET_ALL_OFFERING = "GET_ALL_OFFERING"
export const GET_ALL = "GET_ALL"

// ACTION FOR TRANSACTION PRODUCT
export const GET_ALL_TRANSACTION = "GET_ALL_TRANSACTION"
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";



