// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const SEND_LINK_RESET = "SEND_LINK_RESET";
export const SEND_LINK_ERROR = "SET_LINK_ERROR";
export const GET_LINK_RESET = "GET_LINK_RESET";
export const GET_LINK_ERROR = "GET_LINK_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

// ACTIONS FOR PRODUCTS
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

//ACTIONS FOR OFFERING PRODUCT
export const CREATE_OFFERING = "CREATE_OFFERING";
export const OFFERING_ERROR = "OFFERING_ERROR";
export const GET_OFFER = "GET_OFFER";
export const GET_ALL_OFFERING = "GET_ALL_OFFERING";
export const GET_ALL = "GET_ALL";
export const DELETE_OFFERING = "DELETE_OFFERING";
export const UPDATE_OFFERING = "UPDATE_OFFERING";

// ACTION FOR TRANSACTION PRODUCT
export const GET_ALL_TRANSACTION = "GET_ALL_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";

// ACTION FOR NOTIFICATION
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
